name: Sync Labels
on:
  push:
    branches: [main]
    paths: ['.github/config/labels.yml']

permissions:
  issues: write
  labels: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        manifest: .github/config/labels.yml
